version: 2.1
orbs:
  slack: circleci/slack@4.12.5
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create docker network
          command: docker network create grid
      - store_test_results:
          path: ~/test-results/junit/
      - store_artifacts:
          path: ~/testng/results/
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master