version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Validate Branch Name Starts with JiraTicket
          command: sudo sh ./sh/validateJira.sh -c true
workflows:
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master