version: 2.1
orbs:
  slack: circleci/slack@4.12.5
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Validate Branch Name Starts with JiraTicket
          command: . sh/validateJira.sh
workflows:
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master